In [29]:
import numpy as np

#Create a dataset with 100 records.

# Project: Software Company Project Sales Analysis

# Columns: Project_ID, Client_ID, Project_Type, Team_Size, Project_Value, Cost, Profit, Client_Rating       
#Project_Type: 1=Web App, 2=Mobile App, 3=ERP, 4=AI/ML, 5=Cloud Migration
# Profit = Project_Value - Cost (USD)

sales = np.array([
[2001, 337, 4, 8, 607500, 413100, 194400, 3],
    [2002, 325, 2, 15, 534000, 394500, 139500, 3],
    [2003, 327, 4, 4, 288500, 180300, 108200, 3],
    [2004, 335, 3, 11, 903000, 574800, 328200, 4],
    [2005, 323, 1, 12, 647000, 430500, 216500, 3],
    [2006, 331, 1, 8, 554500, 393700, 160800, 3],
    [2007, 333, 4, 4, 117500, 67900, 49600, 5],
    [2008, 309, 2, 9, 513000, 417300, 95700, 4],
    [2009, 303, 3, 8, 185000, 139200, 45800, 3],
    [2010, 312, 2, 14, 877000, 574300, 302700, 4],
    [2011, 312, 2, 11, 865500, 499500, 366000, 3],
    [2012, 335, 1, 7, 455500, 372100, 83400, 4],
    [2013, 336, 2, 3, 88000, 52400, 35600, 3],
    [2014, 301, 5, 10, 413000, 246400, 166600, 4],
    [2015, 320, 3, 6, 353000, 210200, 142800, 4],
    [2016, 333, 2, 11, 561000, 324500, 236500, 4],
    [2017, 306, 3, 14, 1215000, 1053600, 161400, 4],
    [2018, 332, 5, 7, 212000, 136500, 75500, 5],
    [2019, 305, 2, 14, 198500, 130400, 68100, 5],
    [2020, 319, 3, 9, 65500, 55100, 10400, 3],
    [2021, 332, 3, 9, 424000, 325100, 98900, 3],
    [2022, 312, 4, 12, 270500, 166400, 104100, 3],
    [2023, 314, 3, 13, 548000, 384700, 163300, 5],
    [2024, 311, 4, 14, 1060000, 910900, 149100, 5],
    [2025, 329, 3, 15, 890500, 606700, 283800, 3],
    [2026, 310, 4, 4, 245500, 196100, 49400, 5],
    [2027, 339, 5, 8, 422500, 246600, 175900, 3],
    [2028, 318, 1, 15, 242000, 194700, 47300, 4],
    [2029, 319, 3, 6, 325500, 267400, 58100, 4],
    [2030, 320, 3, 3, 212000, 177800, 34200, 5],
    [2031, 323, 2, 10, 749000, 588600, 160400, 3],
    [2032, 322, 2, 12, 532500, 361900, 170600, 3],
    [2033, 320, 1, 12, 263000, 150500, 112500, 4],
    [2034, 339, 3, 13, 949500, 694600, 254900, 3],
    [2035, 332, 5, 11, 475500, 387500, 88000, 3],
    [2036, 331, 1, 4, 306000, 188700, 117300, 4],
    [2037, 328, 3, 14, 494000, 317700, 176300, 5],
    [2038, 325, 5, 8, 217500, 160400, 57100, 4],
    [2039, 314, 5, 14, 335000, 271900, 63100, 5],
    [2040, 339, 2, 13, 1357000, 1172100, 184900, 4],
    [2041, 319, 1, 15, 1207500, 717200, 490300, 4],
    [2042, 309, 4, 3, 165500, 101600, 63900, 5],
    [2043, 333, 1, 14, 349500, 290000, 59500, 4],
    [2044, 307, 2, 11, 540000, 418800, 121200, 4],
    [2045, 334, 3, 9, 425500, 341300, 84200, 3],
    [2046, 324, 5, 13, 814000, 731600, 82400, 3],
    [2047, 305, 1, 15, 209500, 184000, 25500, 4],
    [2048, 302, 4, 9, 243500, 205700, 37800, 3],
    [2049, 318, 3, 4, 240000, 197200, 42800, 5],
    [2050, 302, 1, 12, 191500, 131800, 59700, 4],
    [2051, 306, 5, 5, 382000, 295800, 86200, 3],
    [2052, 321, 5, 5, 151500, 93100, 58400, 5],
    [2053, 338, 3, 5, 48500, 39500, 9000, 3],
    [2054, 319, 5, 5, 383500, 312600, 70900, 4],
    [2055, 332, 4, 14, 664500, 533200, 131300, 3],
    [2056, 336, 5, 7, 566000, 399400, 166600, 5],
    [2057, 333, 5, 4, 424000, 289300, 134700, 4],
    [2058, 325, 3, 5, 417500, 290900, 126600, 5],
    [2059, 318, 2, 8, 711000, 399300, 311700, 3],
    [2060, 321, 1, 7, 124000, 104800, 19200, 5],
    [2061, 311, 3, 7, 545500, 403500, 142000, 4],
    [2062, 320, 1, 15, 1142500, 783300, 359200, 4],
    [2063, 315, 4, 14, 682500, 506200, 176300, 5],
    [2064, 310, 5, 10, 849500, 681700, 167800, 4],
    [2065, 339, 2, 15, 933000, 637700, 295300, 4],
    [2066, 301, 3, 7, 683000, 574200, 108800, 4],
    [2067, 304, 1, 4, 332500, 289800, 42700, 5],
    [2068, 308, 1, 6, 370500, 254000, 116500, 3],
    [2069, 338, 2, 4, 234500, 140200, 94300, 4],
    [2070, 327, 5, 15, 1015500, 828700, 186800, 3],
    [2071, 335, 5, 5, 158500, 142200, 16300, 4],
    [2072, 308, 4, 8, 57000, 34300, 22700, 4],
    [2073, 329, 3, 5, 99500, 79500, 20000, 3],
    [2074, 315, 3, 15, 163500, 137100, 26400, 4],
    [2075, 320, 1, 5, 246500, 214900, 31600, 3],
    [2076, 301, 2, 9, 74500, 44100, 30400, 5],
    [2077, 325, 5, 15, 359000, 208900, 150100, 4],
    [2078, 333, 3, 9, 280000, 250800, 29200, 4],
    [2079, 326, 2, 14, 1058000, 625100, 432900, 4],
    [2080, 307, 2, 14, 532000, 325500, 206500, 4],
    [2081, 321, 4, 12, 1336000, 1003600, 332400, 4],
    [2082, 311, 1, 12, 278000, 196300, 81700, 3],
    [2083, 338, 5, 10, 717000, 582600, 134400, 4],
    [2084, 335, 5, 10, 468000, 288600, 179400, 4],
    [2085, 308, 3, 13, 479000, 416700, 62300, 5],
    [2086, 320, 3, 8, 77500, 48500, 29000, 3],
    [2087, 337, 4, 15, 680000, 557000, 123000, 4],
    [2088, 334, 3, 14, 919000, 527100, 391900, 4],
    [2089, 328, 3, 7, 110500, 79000, 31500, 4],
    [2090, 325, 2, 8, 121500, 68200, 53300, 3],
    [2091, 302, 3, 12, 189500, 125000, 64500, 4],
    [2092, 329, 4, 14, 844500, 556700, 287800, 3],
    [2093, 319, 1, 4, 72000, 57700, 14300, 3],
    [2094, 304, 1, 3, 23000, 16300, 6700, 5],
    [2095, 310, 4, 6, 220000, 125300, 94700, 3],
    [2096, 322, 2, 8, 307000, 275800, 31200, 4],
    [2097, 329, 5, 5, 304500, 262100, 42400, 4],
    [2098, 320, 1, 9, 916500, 798000, 118500, 4],
    [2099, 324, 5, 10, 811500, 516300, 295200, 4],
    [2100, 334, 1, 15, 763500, 525200, 238300, 5]
])

print("\n===== 1. Create a dataset with 100 records  =====")
  
print (sales)


===== 1. Create a dataset with 100 records  =====
[[   2001     337       4       8  607500  413100  194400       3]
 [   2002     325       2      15  534000  394500  139500       3]
 [   2003     327       4       4  288500  180300  108200       3]
 [   2004     335       3      11  903000  574800  328200       4]
 [   2005     323       1      12  647000  430500  216500       3]
 [   2006     331       1       8  554500  393700  160800       3]
 [   2007     333       4       4  117500   67900   49600       5]
 [   2008     309       2       9  513000  417300   95700       4]
 [   2009     303       3       8  185000  139200   45800       3]
 [   2010     312       2      14  877000  574300  302700       4]
 [   2011     312       2      11  865500  499500  366000       3]
 [   2012     335       1       7  455500  372100   83400       4]
 [   2013     336       2       3   88000   52400   35600       3]
 [   2014     301       5      10  413000  246400  166600       4]
 [   2015  

In [98]:
#2.Explore dataset properties.

print("\n===== Explore dataset properties  =====")

print("shape",sales.shape) #shape 

print("Diamention",sales.ndim) #diamention

print("size",sales.size) # datasize

print("Data type",sales.dtype) # datatype

#Display first and last sales.
print("\n===== first and last sales. =====")

print("First sales",sales[0])  #first
print("last sales",sales[-1]) #Last

#Display min profit and max profit.
print("\n===== min profit and max profit =====")

print("Minimum profit:", sales[:, 6].min())
print("Maximum profit:", sales[:, 6].max())

print("\n===== min project_value and max profit =====")

print("Minimum roject_value:", sales[:, 4].min())
print("Maximum project_value:", sales[:, 4].max())

print("\n===== Total Profit =====")

# Total Profit
print ("Total profit:", sales[:, 6].sum())

# Total cost
print("\n===== Total cost =====")
print("Total cost", sales[:,5].sum())

# Total project value
print("\n===== Total value =====")
print("Total project value", sales[:,4].sum())

# Average Profit
print("\n===== Average Profit =====")
print(sales[:,6].mean())


# Average Project Value
print("\n===== Average project value =====")
print(sales[:,4].mean())

# Average Cost
print("\n===== Average cost =====")
print(sales[:,5].mean())

# Average Team Size
print("\n===== Average Team Size =====")
print(sales[:,3].mean())


# Average Client Rating
print("\n===== Average Client Rating=====")
print(sales[:,6].mean())



# Number of Clients
print("\n===== Number of Clients =====")
unique_clients = np.unique(sales[:,1])
print("Number of unique clients:", len(unique_clients))

# Number of Projects
print("\n===== Number of projects =====")
unique_projects = np.unique(sales[:,0])
print("Number of unique projects:", len(unique_projects))

#Median
print("\n===== profit Median=====")
print("Median profit:", np.median(sales[:, 6]))

#Variance
print("\n===== Variance=====")
print("Variance:", sales[:, 6].var())

#Filter project profit > 50000.
profit = sales[:, 6]
result = profit[profit > 50000]
print("Number of projects:", len(unique_projects))

print("\n===== profit > 50000 =====")
print(result)


#Reshape dataset
sales1 = sales.reshape(8, 100)

print("\n===== Reshape dataset =====")
print(sales1)

#Transpose dataset.
result3 = sales.T
print("\n===== Transpose dataset =====")

print(result3)

# Add 25% bonus to every profit value # broadcasting
bonus_profit = sales[:,6] * 25/100
print(bonus_profit)


===== Explore dataset properties  =====
shape (100, 8)
Diamention 2
size 800
Data type int64

===== first and last sales. =====
First sales [  2001    337      4      8 607500 413100 194400      3]
last sales [  2100    334      1     15 763500 525200 238300      5]

===== min profit and max profit =====
Minimum profit: 6700
Maximum profit: 490300

===== min project_value and max profit =====
Minimum roject_value: 23000
Maximum project_value: 1357000

===== Total Profit =====
Total profit: 12987100

===== Total cost =====
Total cost 34701400

===== Total value =====
Total project value 47688500

===== Average Profit =====
129871.0

===== Average project value =====
476885.0

===== Average cost =====
347014.0

===== Average Team Size =====
9.56

===== Average Client Rating=====
129871.0

===== Number of Clients =====
Number of unique clients: 35

===== Number of projects =====
Number of unique projects: 100

===== profit Median=====
Median profit: 106150.0

===== Variance=====
Variance